baseURL = "/"
languageCode = "en-us"
title = "Volley Visualization"
theme = "minimal"
disqusShortname = "Nate" # delete this to disable disqus comments
#googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "Nate Ngo"
    description = "Volleyball. Data. Visualization. Analysis. Learning."
    githubUsername = "natengo1"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/resources/"
    name = "Resources & More"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

#[[menu.icon]]
#    url = "mailto:me@example.com"
#    name = "envelope-o"
#    weight = 1

[[menu.icon]]
    url = "https://github.com/natengo1/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/natengo1/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/natengo1/"
    name = "linkedin"
    weight = 3

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
